// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaiVdVznbTpQcAgiQLKXDECmH_BFqi8GM',
    appId: '1:733162330357:web:592cb10274fd066afb8dbc',
    messagingSenderId: '733162330357',
    projectId: 'absensi1-42425',
    authDomain: 'absensi1-42425.firebaseapp.com',
    storageBucket: 'absensi1-42425.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1jYylSh2rTzFO0DgpbrllxKZ3PhxRcrk',
    appId: '1:733162330357:android:f363beb0e088e21bfb8dbc',
    messagingSenderId: '733162330357',
    projectId: 'absensi1-42425',
    storageBucket: 'absensi1-42425.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtXMc0PGpX7FSGv1g6oZ-eYZtAU7H4-Cg',
    appId: '1:733162330357:ios:778ef1d4b1ee747efb8dbc',
    messagingSenderId: '733162330357',
    projectId: 'absensi1-42425',
    storageBucket: 'absensi1-42425.firebasestorage.app',
    iosBundleId: 'com.example.attedanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtXMc0PGpX7FSGv1g6oZ-eYZtAU7H4-Cg',
    appId: '1:733162330357:ios:778ef1d4b1ee747efb8dbc',
    messagingSenderId: '733162330357',
    projectId: 'absensi1-42425',
    storageBucket: 'absensi1-42425.firebasestorage.app',
    iosBundleId: 'com.example.attedanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaiVdVznbTpQcAgiQLKXDECmH_BFqi8GM',
    appId: '1:733162330357:web:a14ec934dbfdd0acfb8dbc',
    messagingSenderId: '733162330357',
    projectId: 'absensi1-42425',
    authDomain: 'absensi1-42425.firebaseapp.com',
    storageBucket: 'absensi1-42425.firebasestorage.app',
  );
}
